### ISSUE TITLE
Add User property to Chat Completion request

### ISSUE THREAD

**Issue by marcominerva** [marcominerva/ChatGptNet#28]
The Chat Completion API supports a **User** property, as described here: https://platform.openai.com/docs/api-reference/completions/create#completions/create-user.

> A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.

This property must be added to `ChatGptOptions`.

**Comment by nanny07** [comment]
What about adding it to the `ChatGptParameters` class? It should be useful to be able to modify the property based on some condition: for examples [in the documentation](https://platform.openai.com/docs/guides/safety-best-practices/end-user-ids) it says that it would be best to create one per user.

Putting on the `ChatGptParameters` class will give the developer the option to populate it on every call (maybe checking the authenticated user) rather than one per application

**Comment by marcominerva** [comment]
If you need to popolate it on every call, you can use the `AddChatGpt` overload that provides a `ServiceProvider` and that is called for every request. With this method, you can change even the API key (assuming, for example, that each authenticated user has a different key).
